Parameters:
  VpcId: # Also, this will be the name of the EC2 instance and multiple ofhter AWS resources.
    Type: String
    Description: The VpcId to deploy the SQL Instances
    Default: "Workshop - .NET development on AWS"

  SubnetIds: # "+TheStrong1" is appended by the system.
    Type: CommaDelimitedList
    Description: "The Subnet IDs to deploy the database instances"
    Default: "1,2,3"
    #AllowedPattern: "^\\S{6,}$"

Resources:
  DatabaseSubnetGroup7D60F180:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Database database
      SubnetIds:
        - subnet-0fa739a7c762afe57
        - subnet-06724c68b7493e39c
        - subnet-00d3e031c3467cead
  DatabaseSecurityGroup5C91FDCB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Database database
      SecurityGroupEgress:
        - CidrIp: "0.0.0.0/0"
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId: vpc-0b64ecec5bc52508f
  DatabaseSecret3B817195:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Join
        - ""
        - - "Generated by the CDK for stack: "
          - !Ref "AWS::StackName"
      GenerateSecretString:
        ExcludeCharacters: ' %+~`#$&*()|[]{}:;<>?!''/@"\'
        GenerateStringKey: password
        PasswordLength: 30
        SecretStringTemplate: '{"username":"admin"}'
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  DatabaseSecretAttachmentE5D1B020:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref "DatabaseSecret3B817195"
      TargetId: !Ref "DatabaseB269D8BB"
      TargetType: AWS::RDS::DBInstance
  DatabaseB269D8BB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.m5.large
      AllocatedStorage: "100"
      CopyTagsToSnapshot: true
      DBSubnetGroupName: !Ref "DatabaseSubnetGroup7D60F180"
      Engine: sqlserver-ee
      MasterUsername: !Join
        - ""
        - - "{{resolve:secretsmanager:"
          - !Ref "DatabaseSecret3B817195"
          - :SecretString:username::}}
      MasterUserPassword: !Join
        - ""
        - - "{{resolve:secretsmanager:"
          - !Ref "DatabaseSecret3B817195"
          - :SecretString:password::}}
      StorageType: gp2
      VPCSecurityGroups:
        - !GetAtt "DatabaseSecurityGroup5C91FDCB.GroupId"
    UpdateReplacePolicy: Snapshot
    DeletionPolicy: Snapshot
